repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Use the latest stable version
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-builtins
          - flake8-bugbear
        args: [--max-line-length=88]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0  # Use the latest stable version
    hooks:
      - id: pylint
        args:
          [
            "--rcfile=.pylintrc", # Link to your config file
          ]
