# Specify when the workflow should run
on:
  push:
    branches:
      - "2.0"
      - "dev"
  pull_request:
    branches:
      - "2.0"
      - "dev"

jobs:
  # Define a job for running tests
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Specify your desired Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Include pytest and other dependencies here

      - name: Run tests
        env:
          VIADOT_CONFIG_PATH: .config/credentials.json.template
        run: |
          sudo apt install libsqliteodbc
          pytest tests/unit

  # Define a job for building and pushing Docker images
  publish-docker-image:
    runs-on: ubuntu-latest
    # Run this job only on a push event to the '2.0' branch
    if: github.ref == 'refs/heads/2.0' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/viadot:${{ github.sha }} # This tags the image with the commit SHA