name: CI

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files

  run-tests:
    timeout-minutes: 15
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rye
        uses: eifinger/setup-rye@v4

      - name: Install dependencies
        run: |
          rye config --set-bool behavior.use-uv=true
          rye sync --no-lock --features=aws

      - name: Run tests
        run: rye run coverage run --branch -m pytest tests/unit -vv

      - name: Validate test coverage
        if: always()
        run: rye run coverage report --fail-under=32
