name: Static Site Prepare

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "mkdocs.yml"
      - "docs/**"

jobs:
  deploy:
    uses: ./.github/workflows/template_static_site_prepare_zensical.yml
    with:
      project_manager: uv
      uv_sync_flags: --group docs
      static_site_branch: static-site
    secrets: inherit # pragma: allowlist secret
