name: Static Site Prepare

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "mkdocs.yml"
      - "docs/**"

jobs:
  deploy:
    uses: dyvenia/workflow-templates/.github/workflows/template-static-site-prepare-zensical.yml@feat/migrate-to-zensical
    with:
      project_manager: uv
      uv_sync_flags: --group docs
      static_site_branch: static-site
    secrets: inherit
